/**
 *         __ __ __                        __ 
 * .-----.|__|  |  |--.----.-----.---.-.--|  |
 * |__ --||  |  |    <|   _|  _  |  _  |  _  |
 * |_____||__|__|__|__|__| |_____|___._|_____|
 *
 * @author	hever barrera batero ; juan diego patino munoz
 * @version	1
 *
 * this class provides a way to store information about the chunks
 * generated by 'Road.java' file, basically that file stores a bunch
 * of objects of this clas in order to save info of the simulation
 */

public class Chunk
{
	private PageOrientation orientedby;
	private Store           store;
	private int             globalId;
	private int             internalId;
	private boolean         displayed;

	public Chunk (final PageOrientation orientation, final int nochunk, final boolean show)
	{
		this.orientedby = orientation;
		this.globalId   = nochunk;
		this.internalId = nochunk % Road.MAXNOTERRAINLENGTH;
		this.store      = null;
		this.displayed  = show;
	}

	public void inaugurateStore (final int tenges)
	{
		this.store = new Store(
			tenges,
			this.orientedby.getModifiedIndexBasedOnInternalId(this.internalId),
			this.displayed
		);
	}

	public Store getStore () { return this.store; }

	public void changevisibility (final boolean to)
	{
		this.displayed = to;
		if (this.store != null)
		{
			this.store.changevisibility(to);
		}
	}
}
